#export PATH=$PATH:/opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/bin
#export PATH=$PATH:/opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/bin


default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :build do
    gradle(
     task: "assemble",
     project_dir: "./android/"
    )
  end

end

