export ANDROID_SDK_ROOT="/root/android-sdk-linux"

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :build do
    gradle(
     task: "assemble",
     project_dir: "./android/"
    )
  end

end

